version: '2'
services:
  client:
    build: ./client
    ports:
      - "80:3000"
    volumes:
      - ./client:/nightlux/client
      - /nightlux/client/node_modules
    restart: on-failure
  api:
    build: ./api
    ports:
      - "8080:3000"
    volumes:
      - ./api:/nightlux/api
      - /nightlux/api/node_modules
    depends_on:
      - "mongo"
    restart: on-failure
  mongo:
    image: mongo:3.4
    volumes:
      - ~/.docker-volumes/nightlux/mongo/:/data/db
